# Generated by Django 2.2.4 on 2019-08-19 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('aadhar_no', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('govtID_card', models.ImageField(upload_to='ID/')),
                ('address_proof', models.ImageField(upload_to='Address_Proof/')),
                ('voter_photo', models.ImageField(upload_to='Passport_Photo/')),
                ('connectionHash', models.CharField(blank=True, max_length=255, null=True)),
                ('voterID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheVoterData',
            fields=[
                ('voter_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('aLine1', models.CharField(max_length=500)),
                ('aLine2', models.CharField(max_length=500)),
                ('s_code', models.IntegerField()),
                ('c_code', models.IntegerField()),
                ('d_code', models.IntegerField()),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionurl', models.CharField(blank=True, max_length=500, null=True)),
                ('connectionHash', models.CharField(blank=True, max_length=255, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoterform.WorkerProfile')),
            ],
        ),
    ]
