# Generated by Django 2.2.4 on 2019-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachevoterdata',
            name='aadhar_no',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
