# Generated by Django 2.2.4 on 2019-08-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0002_auto_20190821_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='voterID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
